### ISSUE TITLE
When I run the code to get traveltime at some points,Some error like ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by maple-xc** [keurfonluu/fteikpy#18]
**Description of the problem**
When I run the code to get traveltime at some points,Some error like ZeroDivisionError: division by zero.
I want to give a random array of positions within a circle to get traveltime.The source is in the center of the circular region.I tried different speed models and grid spacing sizes, which can pass when the array is linear, but may fail when the array becomes random.I wonder if this could have been avoided by code optimization or certain design principles?

**Full code that generated the error**

```python
PASTE YOUR CODE HERE
```
```
import numpy as np
import pyvista
import random

from fteikpy import Eikonal3D, grid_to_meshio

pyvista.set_plot_theme("document")

def getRandomPointInCircle(num, radius, centerx, centery):
    
    # Polar coordinates generate a random array within a ring
    samplePoint = []
    for i in range(num):
        theta = random.random() * 2 * np.pi
        r = random.uniform(0, radius ** 2) 
        x = np.cos(theta) * (r ** 0.5) + centerx
        y = np.sin(theta) * (r ** 0.5) + centery
        samplePoint.append([x, y])

    return samplePoint
def main():
 
    # Observation system ：Polar coordinates generate a random array within a ring
    num = 50
    radius = 12
    centerx,centery = 5, 5
    receiver = np.array(getRandomPointInCircle(num, radius, centerx, centery))

    # Velocity model
    velocity_model = np.ones((60, 200, 200))
    dz, dx, dy = 0.5, 0.5, 0.5
    velocity_model[:10]=velocity_model[:10]*500
    velocity_model[11:30]=velocity_model[11:30]*800
    velocity_model[31:60]=velocity_model[31:60]*1200

    # Solve Eikonal at source
    eik = Eikonal3D(velocity_model, gridsize=(dz, dx, dy),origin=(0,-50,-50))
    #eik.smooth(2.5)
    tt = eik.solve((0, 0, 0), nsweep=3, return_gradient=True)
    ttgrid = tt.grid.ravel()

    # Trace rays for 50 locations
    end_points = np.zeros((num, 3)) #z、x、y
    end_points[:,1] = receiver[:,0] 
    end_points[:,2] = receiver[:,1]
    rays = tt.raytrace(end_points)

    trays = [tt(ray) for ray in rays]

if __name__ == '__main__':
    main()
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```
![image](https://user-images.githubusercontent.com/29663384/155538453-8d4655f9-4dbf-4483-9ea5-8aae6a18a319.png)

**System information**

* Operating system: Windows 10
* Python installation (Anaconda, system, ETS):Anaconda
* Version of Python:3.6.1
* Version of this package:latest

**Comment by maple-xc** [comment]
I configured python=3.8.5, but still seem to have some problems  
![image](https://user-images.githubusercontent.com/29663384/155839455-3a9acd70-ea21-4edc-b6dc-e4d4c064817f.png)
When I just change this line of code:
centerx,centery = 50, 50 and eik = Eikonal3D(velocity_model, gridsize=(dz, dx, dy))
The code works fine, but it doesn't seem to get the desired result

**Comment by maple-xc** [comment]
Hi @keurfonluu 
Your work has been very helpful to me.
Thank you so much for your assistance！

**Comment by keurfonluu** [comment]
Forgot to mention that I've pushed the update v2.3.3 that fixes this issue. Closing this issue.
