### ISSUE TITLE
How to trace the ray inside a cylinderal volume?

### ISSUE THREAD

**Issue by David-zw** [keurfonluu/fteikpy#19]
**Description of the desired feature**
Hi, @keurfonluu
In the laboratory, the sample is a usually cylinder column. So, would you please add a feature to calculte the traveltime and trace the ray inside a cylinder area ? Thank you

**Are you willing to help implement and maintain this feature?** Yes/No
Yes

**Comment by keurfonluu** [comment]
Hi @David-zw ,

Not sure what you mean since it's already possible to do with the current solvers in Cartesian coordinates:

 - If your sample is heterogeneous, you can use the 3D Eikonal solver and you can optionally set the velocities outside the physical domain delimited by the cylinder to a low value.
 - If your sample if horizontally homogeneous, you can use the 2D Eikonal solver with the radial coordinate of your sources and receivers equal `r = (x**2 + y**2) ** 0.5`.

**Comment by David-zw** [comment]
Hi @keurfonluu ,
I have found that the problem I encountered should be not be from the shape of the region. 
When I trace the rays in a homogeneous media, and set nsweep>1, some rays could not be correctely traced(See the figure below). 
![image](https://user-images.githubusercontent.com/12843072/160323247-54e53da0-1dc2-415c-9fd6-875ce92d556e.png)
Beisides，the wrong raytracing randomly appeared.  Sometimes, the ray may be traced correcotely, but  it may be traced uncorrectely at another time. It seems that there was a bug in the raytrace solver.  Here is my code. 
`#%% 
import numpy as np
from fteikpy import Eikonal3D
import matplotlib.pyplot as plt
# grid parameters
dz,dx,dy = 2.5,2.5,2.5  
# The size of Rock
l_z,l_x,l_y = 125.+2*dz,50+2*dx,50.+2*dy
nz=int(np.ceil(l_z/dz)) 
nx=int(np.ceil(l_x/dx)) 
ny=int(np.ceil(l_y/dy)) 
dims=(nz,nx,ny) 
x=np.arange(-dx,l_x,dx)
y=np.arange(-dy,l_y,dy)
z=np.arange(-dz,l_z,dz)
# 
Z,X,Y = np.mgrid[-dz/2:l_z-dz:dz,-dx/2:l_x-dx:dx,-dy/2:l_y-dy:dy]
# Valid Bounds
vb2=np.zeros(dims)
vb2[(((X-25)**2+(Y-25)**2)<=25**2) & (Z>=0) & (Z<=125)]=1
# Velocity model
vel = 5*np.ones(dims)
vel[vb2==0]=0.5
slowness=1/vel
# Probe position
Nrz,Nrc = 5,4
radius_mm=25
theta=np.linspace(0,2*np.pi,Nrc+1)
theta=np.delete(theta,Nrc)
zr=np.linspace(6.5,118.5,Nrz)
xr=radius_mm*np.cos(theta)+25
yr=radius_mm*np.sin(theta)+25

probe_posxy=np.tile(np.vstack((xr,yr)).T,(Nrz,1))
probe_posz=np.tile(zr.T,(Nrc,1)).T.reshape((Nrz*Nrc,1))
probe_pos=np.hstack((probe_posz,probe_posxy))    
# Source coordinates
src=probe_pos
Ns=len(src)
# Receiver coodinates

rcv = list(range(0,Ns))
for i in np.arange(0,Nrc):
    for j in np.arange(0,Nrz):
        temp = np.delete(probe_pos,np.arange(0,Ns,Nrc)+i,axis=0) 
        rcv[Nrc*j+i] = temp
#%%   
Ns=len(src)
temp=np.linspace(0,nx-2,9)
nnx=np.zeros((5,)).astype(np.int64)
for i in np.arange(0,5):
    nnx[i]=int(np.ceil(temp[i+2]))
    
temp=np.linspace(0,ny-2,9)
nny=np.zeros((5,)).astype(np.int64)
for i in np.arange(0,5):
    nny[i]=int(np.ceil(temp[i+2]))
    
temp=np.linspace(0,nz-2,9)
nnz=np.zeros((5,)).astype(np.int64)
for i in np.arange(0,5):
    nnz[i]=int(np.ceil(temp[i+2]))
# Solve Eikonal at source
eik = Eikonal3D(vel, gridsize=(dz, dx, dy),origin=(z[0],x[0],y[0]))
for i in range(0,Ns):
    ns=i
    tt = eik.solve(src[ns], nsweep=3, return_gradient=True)
    
    # Raytracing
    
    ray = tt.raytrace(rcv[ns], honor_grid=True)
    mf=len(rcv[i])
    for j in range(mf):
        # Find cell indices along raypath
        nr=j
        if ray[nr].shape[0]<3:
            print('shot %d,recieve %d'%(ns,nr))
        midpoints = 0.5 * (ray[nr][1:] + ray[nr][:-1])
        iz = np.searchsorted(tt.zaxis, midpoints[:, 0], side="right") - 1
        ix = np.searchsorted(tt.xaxis, midpoints[:, 1], side="right") - 1
        iy = np.searchsorted(tt.yaxis, midpoints[:, 2], side="right") - 1
        # Integrate along raypath
        M = np.zeros_like(vel)
        M[iz, ix, iy] = np.linalg.norm(ray[nr][1:] - ray[nr][:-1], axis=1)
        
        # Check results
        print(f"Analytical: {np.linalg.norm(src[ns] - rcv[ns][nr,:])/5}")
        print(f"Calculated (interpolation): {tt(rcv[ns][nr,:])}")
        print(f"Calculated (raytracing): {M.ravel() @ slowness.flatten()}")
        #
        plt.figure(0)
        plt.clf()
        ax = plt.axes(projection='3d')
        # plt.pcolor(x,y,z,M)
        for k in range(0,Ns):
            ax.plot3D(src[k][1],src[k][2],src[k][0],'bo')
        for k in range(0,len(rcv[ns])):
            ax.plot3D(rcv[ns][k,1],rcv[ns][k,2],rcv[ns][k,0],'ro')
        ax.plot3D((src[ns][1],rcv[ns][nr,1]),(src[ns][2],rcv[ns][nr,2]),(src[ns][0],rcv[ns][nr,0]),'b')
        ax.plot3D(ray[nr][:,1],ray[nr][:,2],ray[nr][:,0],'r')
        ax.set_xlabel('X Axes')
        ax.set_ylabel('Y Axes')
        ax.set_zlabel('Z Axes')
        ax.set_xlim(x[0],x[-1])
        ax.set_ylim(y[0],y[-1])
        ax.set_zlim(z[0],z[-1])
        # plt.axis('image')
        plt.grid
        plt.box()
        plt.pause(0.01)`

**Comment by keurfonluu** [comment]
Hi @David-zw ,

I have run your code, and all the ray traced are correct. Which version of `fteikpy` are you using?
I know that the latest version `2.3.2` is fixing a couple of issues, so please at least update to that version:
`pip install fteikpy -U`

**Comment by keurfonluu** [comment]
Unrelated to your problem, I also noted a high discrepancy between the analytical solution and the one given by the interpolation.
There is something wrong in the way you defined your velocity model. I would suggest the following code instead:

```python
dz, dx, dy = 2.5, 2.5, 2.5
nz, nx, ny = 51, 21, 21
z = np.arange(nz) * dz
x = np.arange(nx) * dx
y = np.arange(ny) * dy
Z, X, Y = np.meshgrid(z, x, y, indexing="ij")
vel = np.where(((X - 25.0) ** 2 + (Y - 25.0) ** 2) ** 0.5 <= 25.0, 5.0, 0.5)
```

**Comment by David-zw** [comment]
Hi, @keurfonluu 
    I have updated the fteikpy to the latest version and revised the code according to your comments. But, the problem still appeared.  The code and the result are listed below.  
`
import h5py
import numpy as np
from fteikpy import Eikonal3D
import matplotlib.pyplot as plt

# grid parameters
dz, dx, dy = 2.5, 2.5, 2.5
nz, nx, ny = 51, 21, 21
dims = (nz, nx, ny)
z = np.arange(nz) * dz
x = np.arange(nx) * dx
y = np.arange(ny) * dy
Z, X, Y = np.meshgrid(z, x, y, indexing="ij")
Zg, Xg, Yg = np.meshgrid(z[0:-1]+dz/2, x[0:-1]+dx/2, y[0:-1]+dy/2, indexing="ij")

# Velocity model
vel = np.where(((X - 25.0) ** 2 + (Y - 25.0) ** 2) ** 0.5 <= 25.0, 5.0, 0.5)
vg = np.where(((Xg - 25.0) ** 2 + (Yg - 25.0) ** 2) ** 0.5 <= 25.0, 5.0, 0.5)
slowness = 1/vg

# Probe position
Nrz, Nrc = 5, 4
radius_mm = 25
theta = np.linspace(0, 2*np.pi, Nrc+1)
theta = np.delete(theta, Nrc)
zr = np.linspace(6.5, 118.5, Nrz)
xr = radius_mm*np.cos(theta)+25
yr = radius_mm*np.sin(theta)+25
probe_posxy = np.tile(np.vstack((xr, yr)).T, (Nrz, 1))
probe_posz = np.tile(zr.T, (Nrc, 1)).T.reshape((Nrz*Nrc, 1))
probe_pos = np.hstack((probe_posz, probe_posxy))

# Source coordinates
src = probe_pos
Ns = len(src)

# Receiver coodinates
rcv = list(range(0, Ns))
for i in np.arange(0, Nrc):
    for j in np.arange(0, Nrz):
        temp = np.delete(probe_pos, np.arange(0, Ns, Nrc)+i, axis=0)
        rcv[Nrc*j+i] = temp

# Solve Eikonal at source
eik = Eikonal3D(vel, gridsize=(dz, dx, dy), origin=(z[0], x[0], y[0]))
ns = 0
tt = eik.solve(src[ns], nsweep=3, return_gradient=True)

# Raytracing
ray = tt.raytrace(rcv[ns], honor_grid=True)

# Find cell indices along raypath
nr = 11
midpoints = 0.5 * (ray[nr][1:] + ray[nr][:-1])
iz = np.searchsorted(tt.zaxis, midpoints[:, 0], side="right") - 1
ix = np.searchsorted(tt.xaxis, midpoints[:, 1], side="right") - 1
iy = np.searchsorted(tt.yaxis, midpoints[:, 2], side="right") - 1

# Integrate along raypath
M = np.zeros_like(vg)
M[iz, ix, iy] = np.linalg.norm(ray[nr][1:] - ray[nr][:-1], axis=1)

# Check results
print(f"Analytical: {np.linalg.norm(src[ns] - rcv[ns][nr,:])/5}")
print(f"Calculated (interpolation): {tt(rcv[ns][nr,:])}")
print(f"Calculated (raytracing): {M.ravel() @ slowness.flatten()}")

# plotting
plt.figure(0)
plt.clf()
ax = plt.axes(projection='3d')
# plot cylinder
cu = np.linspace(0, 2*np.pi, 50) 
cx = 25*np.cos(cu)+25  
cy = 25*np.sin(cu)+25  
cz1 = np.zeros(len(cu))
cz2 = 125*np.ones(len(cu))
ax.plot3D(cx,cy,cz1, 'k-')
ax.plot3D(cx,cy,cz2, 'k-')
ax.plot3D(np.zeros(10),25*np.ones(10),np.linspace(0,125,10), 'k-')
ax.plot3D(25*np.ones(10),np.zeros(10),np.linspace(0,125,10), 'k-')
ax.plot3D(50*np.ones(10),25*np.ones(10),np.linspace(0,125,10), 'k-')
ax.plot3D(25*np.ones(10),50*np.ones(10),np.linspace(0,125,10), 'k-')
# plot source
ax.plot3D(src[ns][1], src[ns][2], src[ns][0], 'bo')
# plot receiver
ax.plot3D(rcv[ns][nr, 1], rcv[ns][nr, 2],rcv[ns][nr,0],'ro')
h1,=ax.plot3D((src[ns][1], rcv[ns][nr, 1]), (src[ns][2],rcv[ns][nr,2]),(src[ns][0],rcv[ns][nr,0]),'b')
h2,=ax.plot3D(ray[nr][:, 1], ray[nr][:, 2],ray[nr][:,0],'r')
ax.legend([h1,h2],['True ray','Traced ray'])
ax.set_xlabel('X Axes')
ax.set_ylabel('Y Axes')
ax.set_zlabel('Z Axes')
ax.set_xlim(x[0], x[-1])
ax.set_ylim(y[0], y[-1])
ax.set_zlim(z[0], z[-1])
# plt.axis('image')
plt.grid
plt.box()
plt.show()

`
#The results:
Analytical: 18.227451824103117
Calculated (interpolation): 1.6624138284916826e+16
Calculated (raytracing): 18.25140948151686
![image](https://user-images.githubusercontent.com/12843072/160815973-f4d67019-290a-4077-b0a6-ce2afa9e82b1.png)

**Comment by keurfonluu** [comment]
Hi @David-zw,

Sorry for the late reply.

This kind of deviations from the "true" ray are expected. The traveltime gradients are calculated by numerical differentiation. During the ray tracing, errors are accumulated along the integration path, so the tracer will likely deviate the farther it goes from the target point. To reduce the numerical errors, simply reduce your grid size, e.g.:

```python
dz, dx, dy = 1.25, 1.25, 1.25
nz, nx, ny = 101, 41, 41
```

The smaller the grid size, the smaller the accumulated error during the ray tracing.
