### ISSUE TITLE
Some question about this pacakge

### ISSUE THREAD

**Issue by xichaoqiang** [keurfonluu/fteikpy#24]
From the paper of Noble et al.2014.

The hybrid  scheme has very good performance that combines a spherical approximation when close to the source and a plane
wave approximation when far away.

From _fteik2d.py I know there is some condition to choose plane wave or spherical wave.

I am not sure is the hybrid  scheme applied in  _fteik3d.py.

Do you know this ?

**Comment by keurfonluu** [comment]
Hi @xichaoqiang,

Unfortunately, no, the spherical operator near the source has not been implemented yet in 3D.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.

**Comment by xichaoqiang** [comment]
Is there any plan to apply hybrid schedule to 3d  ?
