### ISSUE TITLE
Can't change the position of source in the sample.py

### ISSUE THREAD

**Issue by xichaoqiang** [keurfonluu/fteikpy#3]
**Description of the problem**

I can't set the poisition to  (10.0,10.0) but to (10.0+1e-3,10.0+1e-3)  or (10.5,10.5)  

**Full code that generated the error**

My test code is in the attachment.

[sample.zip](https://github.com/keurfonluu/fteikpy/files/5825694/sample.zip)

**Full error message**

```
Traceback (most recent call last):
  File "sample.py", line 37, in <module>
    trays = [tt(ray) for ray in rays]
  File "sample.py", line 37, in <listcomp>
    trays = [tt(ray) for ray in rays]
  File "C:\Users\xcq\AppData\Roaming\Python\Python38\site-packages\fteikpy\_grid.py", line 91, in __call__
    return vinterp2d(
ZeroDivisionError: division by zero
```

**System information**

* Operating system:Winodws 10
* Python install

ation (Anaconda, system, ETS):Anaconda
* Version of Python:3.8
* Version of this package:2.0

**Comment by keurfonluu** [comment]
Hi @xichaoqiang,

I can't reproduce this error (I tried with Python 3.7.7 on Windows 10 and Python 3.8.5 on Ubuntu 20.04).

I tested both

```python
tt = eik.solve((10.0 + 1.0e-3, 10.0 + 1.0e-3), nsweep=3, return_gradient=True)
```

and

```python
tt = eik.solve((10.5, 10.5), nsweep=3, return_gradient=True)
```

and the full script runs correctly in both cases.

**Comment by xichaoqiang** [comment]
Thanks for your reply.Try(10.0,10.0).

**Comment by keurfonluu** [comment]
Should be fixed now. Please upgrade to version `2.0.1`: `pip install -U fteikpy --user`.

**Comment by xichaoqiang** [comment]
> pip install -U fteikpy --user

Good job.It works.
